
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Thu Jun 06 23:46:14 BRT 2019
//----------------------------------------------------

package datatype;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int ID = 9;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int EXTENDS = 7;
  public static final int VIRG = 5;
  public static final int LPAREN = 3;
  public static final int CONST = 8;
  public static final int CLASS = 2;
}

